### ISSUE TITLE
Extract labels shown in the webapp

### ISSUE THREAD

**Issue by shrrag21** [NLPReViz/emr-nlp-server#2]
Hi, thanks for your wonderful work!

Just wondering if there's a straightforward way to extract the labels predicted for each variable in the interface and store them on a disk (as a .csv file perhaps)?

Thanks in advance.

**Comment by trivedigaurav** [comment]
Yes, it is possible to download the predictions as a json file.

I have added a new feature in the UI to do this: https://github.com/NLPReViz/emr-vis-web/commit/2aa99fdf88a965d69bce8a24e119233867342a72

<img width="536" alt="Export table" src="https://user-images.githubusercontent.com/377867/130282547-9dd7b1ad-cd52-4048-b204-0b3417ce854f.png">

Otherwise, the following call to the backend service will give you the same information:
`http://localhost:8080/emr-nlp-server/rest/server/getVarGridObj/[model version]/[dataset version]`
For example, http://localhost:8080/emr-nlp-server/rest/server/getVarGridObj/modelList.0..xml/feedbackIDList.xml

**Comment by srag21** [comment]
Super useful feature! 

Appreciate the help.

**Comment by shrrag21** [comment]
Super useful feature!

Appreciate the help.
